### ISSUE TITLE
Upgrade project to sbt 1.0

### ISSUE THREAD

**Issue by ignasi35** [lagom/lagom.github.io#123]
Bumping the sbt version will allow using newer AkkaHTTp instead of 

`libraryDependencies += "com.typesafe.akka" % "akka-http-experimental_2.10" % "2.0.4"`

**Comment by TimMoore** [comment]
I took a look at this once, and it's going to be a bit tricky.

We'll need to update [all of the plugins](https://github.com/lagom/lagom.github.io/blob/template/project/plugins.sbt) to 1.x-compatible versions, but at least [`sbt-concat`](https://github.com/noisycr1cket/sbt-concat) has been abandoned without any recent updates, so we'll need to find an alternative. Hopefully there is a simple one, but I asked once on Lightbend Slack and nobody responded. I am pretty much in the dark on `sbt-web` things... 😦

**Comment by dwijnand** [comment]
sbt-concat 0.2.0 with sbt 1 support is out:

http://dl.bintray.com/sbt/sbt-plugin-releases/net.ground5hark.sbt/sbt-concat/scala_2.12/sbt_1.0/0.2.0/
