### ISSUE TITLE
Rework downloads page

### ISSUE THREAD

**Issue by jroper** [lagom/lagom.github.io#19]
The downloads page needs to be reworked.  It needs to provide a clean user experience for the following:

* Helping the user understand what needs to be downloaded, what purpose those things serve
* Helping the user understand what choices they have to make, eg choose between Maven/sbt, Scala/Java
* Links to pre-bundled templates that can be downloaded and run with nothing but a JDK
* A smooth transition from the downloads page into the Lagom installation and getting started documentation

**Comment by TimMoore** [comment]
We also want to remove references to Activator and guide people along the right path for getting started with either Maven or sbt.
