### ISSUE TITLE
Lagom Documentation Code Samples not always scrollable horizontally on a phone

### ISSUE THREAD

**Issue by jlprat** [lagom/lagom.github.io#2]
Code listings on the documentation page are able to be scrolled horizontally only when the code listing is on the bottom section of the screen. Once they are on the middle or top part of the screen, code listings fail to scroll horizontally.
I tried to do a remote debugging on the device, but when inspecting, the problem is not reproducible.

Browser: Chrome 49.0.2623.91 
OS: Android 4.4.2

**Comment by jroper** [comment]
The current website is only temporary, we're working on a full responsive website that will completely replace the current documentation.
