### ISSUE TITLE
Fix _Blogs via Scoop.it_ given that it is not related to lagom framework

### ISSUE THREAD

**Issue by Guisanpea** [lagom/lagom.github.io#207]
At the bottom of the page there is a link _Blogs via Scoop.it_ which should show blog posts about the framework. However someone has chosen it to show some lifestyle blog posts.

I don't know how scoop.it works but however I thing that either the link has to be changed or removed.

**Comment by ignasi35** [comment]
I works as expected on my machine:

 - the blogs scoopt.it lists are related to Play framework (at least the first dozen and a half).

I don't think this issue is related to the playframework site.

**Comment by TimMoore** [comment]
@ignasi35 the links from the Lagom site are far less useful: https://www.scoop.it/topic/lagom

I have no idea how this content is sourced. https://www.scoop.it/topic/lagomframework is a 404.

I agree with @Guisanpea that if we can't figure out how to make this useful, we should just remove the link.

**Comment by ignasi35** [comment]
> @ignasi35 the links from the Lagom site are far less useful: [scoop.it/topic/lagom](https://www.scoop.it/topic/lagom)

🤦🏼‍♂️ Too much switching back and forth between lagom and playframework lead me to validate the wrong link. Thanks for raising this @TimMoore 

> I have no idea how this content is sourced. [scoop.it/topic/lagomframework](https://www.scoop.it/topic/lagomframework) is a 404.
> 
> I agree with @Guisanpea that if we can't figure out how to make this useful, we should just remove the link.

Yeah. The _lagom_ link to scoop seems to be wrong. I'll PR.

**Comment by dwijnand** [comment]
Original introduction: https://github.com/playframework/playframework.com/commit/355e4e56258da99ce77493c9821c1c7bcbd0c3d5#diff-93aa8ca98dfb5a96e7a0a2b34ef6fb35R110
