### ISSUE TITLE
Enhancement request: default search version

### ISSUE THREAD

**Issue by rstento** [lagom/lagom.github.io#22]
Currently when you search the doc, the 1.0 version of the docs is searched by default. You have to explicitly select a different version from the dropdown menu. The default version should probably be the latest stable release.

Also, when you move to a new page, the version goes back to 1.0. It would be nice to persist the selection until the visitor changes it. I almost think I'd like more of the functionality of radio buttons than of a dropdown, but that might be messy after many releases.

**Comment by ignasi35** [comment]
IIUC with latest setup prepared by algolia this is solved.
