### ISSUE TITLE
Remove invalid `Icon\r` files

### ISSUE THREAD

**Issue by ignasi35** [lagom/lagom.github.io#38]
As attempted by @TimMoore in https://github.com/lagom/lagom.github.io/commit/52be3065c3893779fefcc72b465f807f40aa9142 we have to remove 3 weird files (0-byte, CR reserved char on the filename).

Those are rebuilt nightly by vegemite so we'd have to get this solved in the core repo or the build machine (?).

**Comment by ignasi35** [comment]
This issue is preventing development on Windows machines.

**Comment by TimMoore** [comment]
@ignasi35 I don't think these were brought back by Vegemite, but by this commit 04f3cf60a56d1e85be13930bfe17b48d670728a4

Is that commit something you added? It doesn't look like it belongs on the `template` branch.

**Comment by ignasi35** [comment]
You are correct, I think that commit is a wrong rebase of `master` into `template`

**Comment by TimMoore** [comment]
OK then I think it is fixed by the revert, but let's watch to see if they return.
