### ISSUE TITLE
Adjust top-level nav "Get Started" to "Try Lagom"

### ISSUE THREAD

**Issue by rstento** [lagom/lagom.github.io#57]
In the usability studies we conducted, there was a bit of confusion over the "Get Started" tab in the nav bar. Some users were looking for "Download", (which was the tab name before, but also caused confusion). Also, lightbend.com is going to change their button to say "Try Lagom" so this issue is to change "Get Started" to "Try Lagom" and see if that helps new visitors navigate more easily.

**Comment by TimMoore** [comment]
Fixed in #58
