### ISSUE TITLE
Lagom documentation is down. 

### ISSUE THREAD

**Issue by Prithvirajbilla** [lagom/lagom.github.io#59]
https://www.lagomframework.com/documentation/ returns
` <!DOCTYPE html>GitHub Pages is temporarily down for maintenance.</html>`
but http://lagom.github.io works
But the github status (https://status.github.com/) says that `All systems are operational`

Not sure if this is a issue.

**Comment by ignasi35** [comment]
Hi @Prithvirajbilla , thanks for the info. 
ATM I can't reproduce the issue. I suspect it's a problem related to the CDN we're using in front of GithubPages which would explain why I can't see the failure and also why Github pages reports no downtime.

**Comment by ignasi35** [comment]
I'm seeing alerts wrt Github pages now and Lagom Docs is down. Rest of Lagom Site still seems to be online.

![screen shot 2017-03-27 at 15 44 06](https://cloud.githubusercontent.com/assets/762126/24359345/5f554240-1304-11e7-811a-a7e769309eb1.png)

**Comment by ignasi35** [comment]
Thanls @Prithvirajbilla for reporting! ;-)

**Comment by Prithvirajbilla** [comment]
Thanks. And It is now back to normal.
