### ISSUE TITLE
pathCall() and restCall() cannot accept multi-value parameters

### ISSUE THREAD

**Issue by bmatthews68** [lagom/lagom.github.io#60]
I would like to be able to bind multi-value parameters using pathCall() and restCall() as illustrated by the snippet below:

```scala
trait UserService extends Service {
    def lookupByUsername(tenantId: String, username: Seq[String])
    override final def descriptor = {
        import Service._
        named("users").withCalls {
            restCall(Method.GET, "/tenants/:tenantId/users?username", lookupByUsername _)
        } 
    }
}
```

```bash
curl http://localhost:9000/tenants/abcdef/users?username=ghijkl&username=mnopqr&username=stuvwx
```

**Comment by ignasi35** [comment]
Hi @bmatthews68 , thanks for your suggestion. 

This repo is only to serve the lagom static page so I will move your issue to github.com/lagom/lagom and close this. See https://github.com/lagom/lagom/issues/643

Regards

**Comment by bmatthews68** [comment]
Hi Ignasi,

Sorry for posting in the wrong repo and thank you for moving it.

Kind regards,
Brian

http://btmatthews.com
http://ie.linkedin.com/in/bmatthews68
https://plus.google.com/+BrianMatthews68
http://twitter.com/bmatthews68
https://www.facebook.com/bmatthews68
http://blog.btmatthews.com/
