### ISSUE TITLE
Disallow non-ASCII characters in blog and doc content

### ISSUE THREAD

**Issue by TimMoore** [lagom/lagom.github.io#72]
#46 only enforces ASCII in the blog front-matter, but non-ASCII characters in the post body can also be problematic.

**Comment by ignasi35** [comment]
I think the same `implicit` codec is used in all the file parsing. See https://github.com/lagom/lagom.github.io/blob/6e397ff878c244c70a3089839bca5e117e2ab176/src/main/scala/com/lightbend/lagom/docs/BlogMetaDataParser.scala#L67-L81 . A single file read loads all the file into a tuple `(metadata, blog body)`.

**Comment by TimMoore** [comment]
OK right I thought I had seen it trigger on post content, too. Closing this.
