### ISSUE TITLE
Add 1.4.x preview documentation to the web site

### ISSUE THREAD

**Issue by TimMoore** [lagom/lagom.github.io#77]
Now that 1.4.0-M1 is out, we should add documentation from the `master` branch to the web site.

The documentation generator has a (currently empty) [`previewVersions`](https://github.com/lagom/lagom.github.io/blob/5ce00dfa468c1daf22fb4dc620fdc58fcf766202/src/main/scala/com/lightbend/lagom/docs/DocumentationGenerator.scala#L35-L36) list for this purpose.

**Comment by TimMoore** [comment]
Other than adding it to `previewVersions`, we also need to update the script that updates the site.

**Comment by ignasi35** [comment]
I updated `nightlies` to deploy `master` as `1.4.x/`
