### ISSUE TITLE
Please document withAutoACL

### ISSUE THREAD

**Issue by orefalo** [lagom/lagom.github.io#8]
In reference to my post on gitter. Please document with AutoACL

@orefalo I can’t find it in the doc, so I guess we forgot about it. Please, file a ticket. In a nutshell, by default services’ endpoints are NOT exposed to the service gateway (and are not accessible to the outside world when running in production). If you want all endpoints of a service to be expose, you can do so with Descriptor#withAutoACL(true). If you want a single endpoint to be exposed, you can call withAutoACL(true) on the endpoint definition.

Sincerely,

**Comment by jroper** [comment]
Raised this issue on Lagom, as this is a problem with Lagom, not the website:

https://github.com/lagom/lagom/issues/369
